### ISSUE TITLE
都没验证过helm就发版了

### ISSUE THREAD

**Issue by tzwken** [deepflowio/deepflow-charts#25]
![image](https://github.com/deepflowio/deepflow-charts/assets/65268273/24f0fc46-4b7f-460a-a336-69a68f43d59f)

有的版本部署后，server无限重启，不是数据库表不全，就是各种连不通。社区版基本上都跑不起来。

**Comment by LemonSqi** [comment]
我也是，用了最新版本的 v6.5.010 grafana上no data，查看日志发现ck里数据是空的，server报错az controller connection拿不到，去mysql查看确实connection为空，controller state状态显示为2，也不知道是什么意思，这社区版不光运行不起来，而且还没有完备的手册，在deepflow仓库提issue，基本上都没人支持，支持的人也是在那打太极，压根不好好帮助解决问题，国产开源质量约等于0，基本就不是给你开源，只是拉出来给你看看。
但是话说回来，不先尝试开源的效果，怎么会采购完整功能的 社区版，起码得先自己跑起来看看效果吧，真的是垃圾中的战斗机，受不鸟这种垃圾开源组件

**Comment by liqian1834** [comment]
你们好，DeepFlow 每次发版本之前都有自动化测试
- 完整开源的 [Demo 环境](https://ce-demo.deepflow.yunshan.net/d/Application_Out_Of_The_Box_CN/application-e5bc80-e7aeb1-e58db3-e794a8?orgId=1)，目前社区的 Demo 环境是稳定运行的
![image](https://github.com/deepflowio/deepflow-charts/assets/19233457/dd0389f3-9ed2-4750-8c17-ab8e481771ee)

- 使用手册，[参考官网](https://www.deepflow.io/docs/zh/ce-install/overview/)，具体哪里有问题可以具体提的呢
- 文中提到的 [Issue](https://github.com/deepflowio/deepflow/issues/7091)，社区的小哥一直在支持，毕竟都是为爱发电，事情也确实是多，有时响应慢一些也需要社区的理解。
- DeepFlow 确实是中国开源，但是我们一直在努力尽最大心力让大家用上好的有质量的可观测性产品。哪怕晚上 11 点我们也是在群里给大家解答问题，Issue 也一直是在跟进。如果真的觉得 DeepFlow 不行，请绕道。
